### ISSUE TITLE
Can't login apparently because my Gmail password is too long

### ISSUE THREAD

**Issue by PaddyMac** [rbrasga/SPPD-Team-Manager#2]
First of all, the team manager fails to find SETTINGS.txt even though it's in the same directory. But besides that, I have a long, randomly-generated password on my Google account. I think it's 64 characters long. This is the output I get when trying to log in (I had to type all this by hand because I couldn't copy/paste, but I think it's all correct):

```
Error: Unable to find SETTINGS.txt
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File"SPPD_Team_Manager.py", line 228 in attemptLogin
  File "api\SPPD_API.py", line 117, in checkLoggedIn
  File "api\SPPD_API.py", line 259, in authenticateAll
  File "api\SPPD_API.py", line 137, in getMasterToken
  File "lib\site-packages\gpsoath\__init__.py", line 60, in perform_master_login
  File "lib\site-packages\gpsoath\google.py", line 50, in signature
  File"lib\site-packages\Cryptodome\Cipher\PKCS1_OAEP.py", line 115, in encrypt
ValueError: Plaintext is too long.
```

**Comment by rbrasga** [comment]
It appears the gpsoauth package is limited to 80 characters.

This is a known issue in the third-party library (nothing I can do about it).

https://github.com/simon-weber/gpsoauth/issues/17
